const synonyms = {
  1: [
    { question: "Choose the synonym of 'Happy'", options: ["Sad", "Joyful", "Angry", "Tired"], answer: "Joyful" },
    { question: "Choose the synonym of 'Quick'", options: ["Slow", "Rapid", "Lazy", "Calm"], answer: "Rapid" },
    { question: "Choose the synonym of 'Big'", options: ["Tiny", "Huge", "Little", "Small"], answer: "Huge" },
    { question: "Choose the synonym of 'Smart'", options: ["Clever", "Dull", "Weak", "Lazy"], answer: "Clever" },
    { question: "Choose the synonym of 'Cold'", options: ["Warm", "Hot", "Chilly", "Boiling"], answer: "Chilly" },
    { question: "Choose the synonym of 'Angry'", options: ["Calm", "Furious", "Peaceful", "Quiet"], answer: "Furious" },
    { question: "Choose the synonym of 'Beautiful'", options: ["Ugly", "Pretty", "Bad", "Dirty"], answer: "Pretty" },
    { question: "Choose the synonym of 'Brave'", options: ["Cowardly", "Fearless", "Weak", "Lazy"], answer: "Fearless" },
    { question: "Choose the synonym of 'Rich'", options: ["Wealthy", "Poor", "Needy", "Cheap"], answer: "Wealthy" },
    { question: "Choose the synonym of 'Strong'", options: ["Weak", "Powerful", "Thin", "Soft"], answer: "Powerful" },
  ],
  2: [
    { question: "Choose the synonym of 'Tiny'", options: ["Small", "Huge", "Tall", "Wide"], answer: "Small" },
    { question: "Choose the synonym of 'Fast'", options: ["Rapid", "Slow", "Calm", "Weak"], answer: "Rapid" },
    { question: "Choose the synonym of 'Lazy'", options: ["Idle", "Active", "Quick", "Brave"], answer: "Idle" },
    { question: "Choose the synonym of 'Neat'", options: ["Tidy", "Dirty", "Ugly", "Bad"], answer: "Tidy" },
    { question: "Choose the synonym of 'Sad'", options: ["Joyful", "Unhappy", "Calm", "Excited"], answer: "Unhappy" },
    { question: "Choose the synonym of 'Hot'", options: ["Cold", "Warm", "Chilly", "Freezing"], answer: "Warm" },
    { question: "Choose the synonym of 'Wise'", options: ["Foolish", "Intelligent", "Lazy", "Weak"], answer: "Intelligent" },
    { question: "Choose the synonym of 'Polite'", options: ["Rude", "Courteous", "Angry", "Brutal"], answer: "Courteous" },
    { question: "Choose the synonym of 'Silent'", options: ["Noisy", "Quiet", "Loud", "Busy"], answer: "Quiet" },
    { question: "Choose the synonym of 'Safe'", options: ["Dangerous", "Secure", "Risky", "Weak"], answer: "Secure" },
  ],
  3: [
    { question: "Choose the synonym of 'Begin'", options: ["Start", "End", "Finish", "Close"], answer: "Start" },
    { question: "Choose the synonym of 'Close'", options: ["Shut", "Open", "Far", "Wide"], answer: "Shut" },
    { question: "Choose the synonym of 'Help'", options: ["Assist", "Ignore", "Hurt", "Stop"], answer: "Assist" },
    { question: "Choose the synonym of 'Friend'", options: ["Enemy", "Companion", "Stranger", "Foe"], answer: "Companion" },
    { question: "Choose the synonym of 'Job'", options: ["Work", "Play", "Rest", "Game"], answer: "Work" },
    { question: "Choose the synonym of 'Old'", options: ["Ancient", "Young", "Modern", "Fresh"], answer: "Ancient" },
    { question: "Choose the synonym of 'Love'", options: ["Hate", "Affection", "Anger", "Fear"], answer: "Affection" },
    { question: "Choose the synonym of 'Hard'", options: ["Soft", "Tough", "Weak", "Thin"], answer: "Tough" },
    { question: "Choose the synonym of 'Bright'", options: ["Dark", "Shiny", "Dim", "Dull"], answer: "Shiny" },
    { question: "Choose the synonym of 'Clean'", options: ["Dirty", "Pure", "Bad", "Ugly"], answer: "Pure" },
  ],
  4: [
    { question: "📘 SYNONYM of 'Happy'", options: ["Joyful", "Sad", "Angry", "Gloomy"], answer: "Joyful" },
    { question: "📘 SYNONYM of 'Brave'", options: ["Courageous", "Coward", "Weak", "Shy"], answer: "Courageous" },
    { question: "📘 SYNONYM of 'Big'", options: ["Large", "Small", "Tiny", "Little"], answer: "Large" },
    { question: "📘 SYNONYM of 'Fast'", options: ["Quick", "Slow", "Lazy", "Weak"], answer: "Quick" },
    { question: "📘 SYNONYM of 'Rich'", options: ["Wealthy", "Poor", "Needy", "Weak"], answer: "Wealthy" },
    { question: "📘 SYNONYM of 'Angry'", options: ["Furious", "Calm", "Peaceful", "Happy"], answer: "Furious" },
    { question: "📘 SYNONYM of 'Begin'", options: ["Start", "End", "Finish", "Close"], answer: "Start" },
    { question: "📘 SYNONYM of 'End'", options: ["Finish", "Start", "Open", "Begin"], answer: "Finish" },
    { question: "📘 SYNONYM of 'Beautiful'", options: ["Pretty", "Ugly", "Bad", "Plain"], answer: "Pretty" },
    { question: "📘 SYNONYM of 'Cold'", options: ["Chilly", "Hot", "Warm", "Sunny"], answer: "Chilly" },
  ],

  5: [
    { question: "📘 SYNONYM of 'Small'", options: ["Tiny", "Huge", "Large", "Massive"], answer: "Tiny" },
    { question: "📘 SYNONYM of 'Friend'", options: ["Companion", "Enemy", "Foe", "Rival"], answer: "Companion" },
    { question: "📘 SYNONYM of 'Difficult'", options: ["Hard", "Easy", "Simple", "Clear"], answer: "Hard" },
    { question: "📘 SYNONYM of 'Quick'", options: ["Rapid", "Slow", "Lazy", "Weak"], answer: "Rapid" },
    { question: "📘 SYNONYM of 'Lazy'", options: ["Idle", "Active", "Energetic", "Hardworking"], answer: "Idle" },
    { question: "📘 SYNONYM of 'Clever'", options: ["Smart", "Dull", "Stupid", "Slow"], answer: "Smart" },
    { question: "📘 SYNONYM of 'Happy'", options: ["Cheerful", "Sad", "Angry", "Upset"], answer: "Cheerful" },
    { question: "📘 SYNONYM of 'Strong'", options: ["Powerful", "Weak", "Fragile", "Feeble"], answer: "Powerful" },
    { question: "📘 SYNONYM of 'Fear'", options: ["Terror", "Courage", "Bravery", "Calm"], answer: "Terror" },
    { question: "📘 SYNONYM of 'Answer'", options: ["Reply", "Question", "Ask", "Demand"], answer: "Reply" },
  ],

  6: [
    { question: "📘 SYNONYM of 'Angry'", options: ["Irate", "Calm", "Peaceful", "Happy"], answer: "Irate" },
    { question: "📘 SYNONYM of 'Danger'", options: ["Peril", "Safety", "Calm", "Peace"], answer: "Peril" },
    { question: "📘 SYNONYM of 'Help'", options: ["Assist", "Hinder", "Stop", "Block"], answer: "Assist" },
    { question: "📘 SYNONYM of 'Polite'", options: ["Courteous", "Rude", "Harsh", "Mean"], answer: "Courteous" },
    { question: "📘 SYNONYM of 'Sad'", options: ["Unhappy", "Happy", "Cheerful", "Excited"], answer: "Unhappy" },
    { question: "📘 SYNONYM of 'Quick'", options: ["Swift", "Slow", "Lazy", "Weak"], answer: "Swift" },
    { question: "📘 SYNONYM of 'Lucky'", options: ["Fortunate", "Unlucky", "Poor", "Hopeless"], answer: "Fortunate" },
    { question: "📘 SYNONYM of 'Silent'", options: ["Quiet", "Loud", "Noisy", "Shouting"], answer: "Quiet" },
    { question: "📘 SYNONYM of 'Old'", options: ["Ancient", "Young", "New", "Fresh"], answer: "Ancient" },
    { question: "📘 SYNONYM of 'New'", options: ["Recent", "Old", "Ancient", "Past"], answer: "Recent" },
  ],

  7: [
    { question: "📘 SYNONYM of 'Smart'", options: ["Intelligent", "Dull", "Lazy", "Stupid"], answer: "Intelligent" },
    { question: "📘 SYNONYM of 'Beautiful'", options: ["Attractive", "Ugly", "Plain", "Bad"], answer: "Attractive" },
    { question: "📘 SYNONYM of 'Angry'", options: ["Mad", "Calm", "Happy", "Peaceful"], answer: "Mad" },
    { question: "📘 SYNONYM of 'Brave'", options: ["Valiant", "Cowardly", "Weak", "Fearful"], answer: "Valiant" },
    { question: "📘 SYNONYM of 'Big'", options: ["Huge", "Tiny", "Little", "Small"], answer: "Huge" },
    { question: "📘 SYNONYM of 'Fear'", options: ["Fright", "Courage", "Calm", "Bravery"], answer: "Fright" },
    { question: "📘 SYNONYM of 'Friend'", options: ["Ally", "Enemy", "Foe", "Rival"], answer: "Ally" },
    { question: "📘 SYNONYM of 'House'", options: ["Home", "Street", "Market", "Shop"], answer: "Home" },
    { question: "📘 SYNONYM of 'Important'", options: ["Significant", "Trivial", "Small", "Weak"], answer: "Significant" },
    { question: "📘 SYNONYM of 'Easy'", options: ["Simple", "Hard", "Difficult", "Complicated"], answer: "Simple" },
  ],

  8: [
    { question: "📘 SYNONYM of 'Job'", options: ["Occupation", "Play", "Rest", "Holiday"], answer: "Occupation" },
    { question: "📘 SYNONYM of 'Laugh'", options: ["Giggle", "Cry", "Weep", "Sob"], answer: "Giggle" },
    { question: "📘 SYNONYM of 'Love'", options: ["Affection", "Hate", "Anger", "Dislike"], answer: "Affection" },
    { question: "📘 SYNONYM of 'Mistake'", options: ["Error", "Correct", "Right", "Truth"], answer: "Error" },
    { question: "📘 SYNONYM of 'Move'", options: ["Shift", "Stop", "Still", "Rest"], answer: "Shift" },
    { question: "📘 SYNONYM of 'Peace'", options: ["Calm", "War", "Fight", "Anger"], answer: "Calm" },
    { question: "📘 SYNONYM of 'Quiet'", options: ["Silent", "Noisy", "Loud", "Shouting"], answer: "Silent" },
    { question: "📘 SYNONYM of 'Run'", options: ["Dash", "Walk", "Stop", "Rest"], answer: "Dash" },
    { question: "📘 SYNONYM of 'Sick'", options: ["Ill", "Healthy", "Fit", "Strong"], answer: "Ill" },
    { question: "📘 SYNONYM of 'Work'", options: ["Labor", "Rest", "Sleep", "Play"], answer: "Labor" },
  ],

  9: [
    { question: "📘 SYNONYM of 'Bright'", options: ["Shiny", "Dark", "Dull", "Dim"], answer: "Shiny" },
    { question: "📘 SYNONYM of 'Calm'", options: ["Peaceful", "Angry", "Wild", "Noisy"], answer: "Peaceful" },
    { question: "📘 SYNONYM of 'Cheap'", options: ["Inexpensive", "Costly", "Expensive", "Pricey"], answer: "Inexpensive" },
    { question: "📘 SYNONYM of 'Dangerous'", options: ["Hazardous", "Safe", "Secure", "Harmless"], answer: "Hazardous" },
    { question: "📘 SYNONYM of 'Dark'", options: ["Gloomy", "Bright", "Light", "Clear"], answer: "Gloomy" },
    { question: "📘 SYNONYM of 'Delicious'", options: ["Tasty", "Awful", "Bitter", "Sour"], answer: "Tasty" },
    { question: "📘 SYNONYM of 'Dull'", options: ["Boring", "Exciting", "Lively", "Cheerful"], answer: "Boring" },
    { question: "📘 SYNONYM of 'Empty'", options: ["Vacant", "Full", "Filled", "Occupied"], answer: "Vacant" },
    { question: "📘 SYNONYM of 'Famous'", options: ["Renowned", "Unknown", "Obscure", "Hidden"], answer: "Renowned" },
    { question: "📘 SYNONYM of 'Glad'", options: ["Pleased", "Sad", "Upset", "Angry"], answer: "Pleased" },
  ],

  10: [
    { question: "📘 SYNONYM of 'Hard'", options: ["Difficult", "Easy", "Soft", "Light"], answer: "Difficult" },
    { question: "📘 SYNONYM of 'Huge'", options: ["Enormous", "Tiny", "Little", "Small"], answer: "Enormous" },
    { question: "📘 SYNONYM of 'Idea'", options: ["Thought", "Thing", "Item", "Fact"], answer: "Thought" },
    { question: "📘 SYNONYM of 'Join'", options: ["Unite", "Break", "Leave", "Quit"], answer: "Unite" },
    { question: "📘 SYNONYM of 'Keep'", options: ["Hold", "Lose", "Give", "Drop"], answer: "Hold" },
    { question: "📘 SYNONYM of 'Love'", options: ["Adore", "Hate", "Dislike", "Ignore"], answer: "Adore" },
    { question: "📘 SYNONYM of 'Mean'", options: ["Unkind", "Nice", "Polite", "Gentle"], answer: "Unkind" },
    { question: "📘 SYNONYM of 'Near'", options: ["Close", "Far", "Distant", "Away"], answer: "Close" },
    { question: "📘 SYNONYM of 'Old'", options: ["Elderly", "Young", "New", "Fresh"], answer: "Elderly" },
    { question: "📘 SYNONYM of 'Quick'", options: ["Rapid", "Slow", "Lazy", "Weak"], answer: "Rapid" },
  ],

  11: [
    { question: "📘 SYNONYM of 'Quiet'", options: ["Silent", "Loud", "Noisy", "Wild"], answer: "Silent" },
    { question: "📘 SYNONYM of 'Right'", options: ["Correct", "Wrong", "False", "Evil"], answer: "Correct" },
    { question: "📘 SYNONYM of 'Sad'", options: ["Unhappy", "Happy", "Glad", "Cheerful"], answer: "Unhappy" },
    { question: "📘 SYNONYM of 'Safe'", options: ["Secure", "Dangerous", "Risky", "Unsafe"], answer: "Secure" },
    { question: "📘 SYNONYM of 'Talk'", options: ["Speak", "Silent", "Mute", "Stop"], answer: "Speak" },
    { question: "📘 SYNONYM of 'Ugly'", options: ["Unattractive", "Beautiful", "Pretty", "Lovely"], answer: "Unattractive" },
    { question: "📘 SYNONYM of 'Value'", options: ["Worth", "Cheap", "Price", "Cost"], answer: "Worth" },
    { question: "📘 SYNONYM of 'Weak'", options: ["Feeble", "Strong", "Powerful", "Tough"], answer: "Feeble" },
    { question: "📘 SYNONYM of 'Yearly'", options: ["Annual", "Monthly", "Weekly", "Daily"], answer: "Annual" },
    { question: "📘 SYNONYM of 'Young'", options: ["Youthful", "Old", "Ancient", "Elderly"], answer: "Youthful" },
  ],

  12: [
    { question: "📘 SYNONYM of 'Angry'", options: ["Annoyed", "Calm", "Happy", "Cheerful"], answer: "Annoyed" },
    { question: "📘 SYNONYM of 'Bright'", options: ["Radiant", "Dark", "Dull", "Dim"], answer: "Radiant" },
    { question: "📘 SYNONYM of 'Calm'", options: ["Serene", "Angry", "Wild", "Noisy"], answer: "Serene" },
    { question: "📘 SYNONYM of 'Dark'", options: ["Dim", "Light", "Clear", "Bright"], answer: "Dim" },
    { question: "📘 SYNONYM of 'Easy'", options: ["Effortless", "Difficult", "Hard", "Tough"], answer: "Effortless" },
    { question: "📘 SYNONYM of 'Fast'", options: ["Speedy", "Slow", "Lazy", "Weak"], answer: "Speedy" },
    { question: "📘 SYNONYM of 'Gift'", options: ["Present", "Curse", "Punishment", "Loss"], answer: "Present" },
    { question: "📘 SYNONYM of 'Hope'", options: ["Expectation", "Fear", "Doubt", "Worry"], answer: "Expectation" },
    { question: "📘 SYNONYM of 'Idea'", options: ["Notion", "Thing", "Fact", "Object"], answer: "Notion" },
    { question: "📘 SYNONYM of 'Join'", options: ["Connect", "Break", "Leave", "Quit"], answer: "Connect" },
  ],

  13: [
    { question: "📘 SYNONYM of 'Kind'", options: ["Gentle", "Cruel", "Harsh", "Rude"], answer: "Gentle" },
    { question: "📘 SYNONYM of 'Lazy'", options: ["Sluggish", "Active", "Energetic", "Hardworking"], answer: "Sluggish" },
    { question: "📘 SYNONYM of 'Move'", options: ["Shift", "Stop", "Still", "Stay"], answer: "Shift" },
    { question: "📘 SYNONYM of 'Nice'", options: ["Pleasant", "Bad", "Ugly", "Rude"], answer: "Pleasant" },
    { question: "📘 SYNONYM of 'Open'", options: ["Unlock", "Close", "Shut", "Seal"], answer: "Unlock" },
    { question: "📘 SYNONYM of 'Poor'", options: ["Needy", "Rich", "Wealthy", "Loaded"], answer: "Needy" },
    { question: "📘 SYNONYM of 'Quick'", options: ["Brisk", "Slow", "Lazy", "Weak"], answer: "Brisk" },
    { question: "📘 SYNONYM of 'Run'", options: ["Sprint", "Walk", "Stop", "Rest"], answer: "Sprint" },
    { question: "📘 SYNONYM of 'Strong'", options: ["Sturdy", "Weak", "Fragile", "Feeble"], answer: "Sturdy" },
    { question: "📘 SYNONYM of 'Tall'", options: ["High", "Short", "Low", "Small"], answer: "High" },
  ],
    14: [
    { question: "📘 SYNONYM of 'Tired'", options: ["Exhausted", "Fresh", "Active", "Energetic"], answer: "Exhausted" },
    { question: "📘 SYNONYM of 'Ugly'", options: ["Hideous", "Beautiful", "Lovely", "Pretty"], answer: "Hideous" },
    { question: "📘 SYNONYM of 'Victory'", options: ["Triumph", "Defeat", "Loss", "Failure"], answer: "Triumph" },
    { question: "📘 SYNONYM of 'Warm'", options: ["Hot", "Cold", "Chilly", "Cool"], answer: "Hot" },
    { question: "📘 SYNONYM of 'Weak'", options: ["Frail", "Strong", "Tough", "Powerful"], answer: "Frail" },
    { question: "📘 SYNONYM of 'Win'", options: ["Succeed", "Lose", "Fail", "Miss"], answer: "Succeed" },
    { question: "📘 SYNONYM of 'Wise'", options: ["Sensible", "Foolish", "Stupid", "Silly"], answer: "Sensible" },
    { question: "📘 SYNONYM of 'Wonderful'", options: ["Marvelous", "Bad", "Ugly", "Awful"], answer: "Marvelous" },
    { question: "📘 SYNONYM of 'Young'", options: ["Juvenile", "Old", "Aged", "Ancient"], answer: "Juvenile" },
    { question: "📘 SYNONYM of 'Yell'", options: ["Shout", "Whisper", "Murmur", "Talk"], answer: "Shout" },
  ],

  15: [
    { question: "📘 SYNONYM of 'Quick'", options: ["Swift", "Slow", "Lazy", "Weak"], answer: "Swift" },
    { question: "📘 SYNONYM of 'Silent'", options: ["Mute", "Loud", "Noisy", "Talkative"], answer: "Mute" },
    { question: "📘 SYNONYM of 'Help'", options: ["Aid", "Block", "Hinder", "Stop"], answer: "Aid" },
    { question: "📘 SYNONYM of 'Angry'", options: ["Enraged", "Calm", "Happy", "Cool"], answer: "Enraged" },
    { question: "📘 SYNONYM of 'Cold'", options: ["Chilly", "Hot", "Warm", "Sunny"], answer: "Chilly" },
    { question: "📘 SYNONYM of 'Friend'", options: ["Mate", "Enemy", "Rival", "Opponent"], answer: "Mate" },
    { question: "📘 SYNONYM of 'Fear'", options: ["Dread", "Courage", "Bravery", "Calm"], answer: "Dread" },
    { question: "📘 SYNONYM of 'Famous'", options: ["Noted", "Unknown", "Hidden", "Obscure"], answer: "Noted" },
    { question: "📘 SYNONYM of 'Truth'", options: ["Reality", "Lie", "Falsehood", "Story"], answer: "Reality" },
    { question: "📘 SYNONYM of 'Travel'", options: ["Journey", "Stay", "Rest", "Stop"], answer: "Journey" },
  ],

  16: [
    { question: "📘 SYNONYM of 'Angry'", options: ["Irate", "Cool", "Calm", "Joyful"], answer: "Irate" },
    { question: "📘 SYNONYM of 'Happy'", options: ["Glad", "Sad", "Upset", "Angry"], answer: "Glad" },
    { question: "📘 SYNONYM of 'Small'", options: ["Petite", "Huge", "Big", "Massive"], answer: "Petite" },
    { question: "📘 SYNONYM of 'Big'", options: ["Gigantic", "Tiny", "Little", "Minute"], answer: "Gigantic" },
    { question: "📘 SYNONYM of 'Clever'", options: ["Bright", "Dull", "Stupid", "Foolish"], answer: "Bright" },
    { question: "📘 SYNONYM of 'Polite'", options: ["Respectful", "Rude", "Harsh", "Cruel"], answer: "Respectful" },
    { question: "📘 SYNONYM of 'Sad'", options: ["Miserable", "Joyful", "Glad", "Cheerful"], answer: "Miserable" },
    { question: "📘 SYNONYM of 'Rich'", options: ["Affluent", "Poor", "Needy", "Weak"], answer: "Affluent" },
    { question: "📘 SYNONYM of 'Work'", options: ["Task", "Rest", "Relax", "Stop"], answer: "Task" },
    { question: "📘 SYNONYM of 'Win'", options: ["Conquer", "Lose", "Fail", "Miss"], answer: "Conquer" },
  ],

  17: [
    { question: "📘 SYNONYM of 'Old'", options: ["Ancient", "Young", "Fresh", "Modern"], answer: "Ancient" },
    { question: "📘 SYNONYM of 'Fast'", options: ["Rapid", "Slow", "Lazy", "Weak"], answer: "Rapid" },
    { question: "📘 SYNONYM of 'Beautiful'", options: ["Lovely", "Ugly", "Plain", "Bad"], answer: "Lovely" },
    { question: "📘 SYNONYM of 'Strong'", options: ["Robust", "Weak", "Fragile", "Feeble"], answer: "Robust" },
    { question: "📘 SYNONYM of 'Happy'", options: ["Content", "Upset", "Sad", "Angry"], answer: "Content" },
    { question: "📘 SYNONYM of 'Fearless'", options: ["Bold", "Cowardly", "Weak", "Afraid"], answer: "Bold" },
    { question: "📘 SYNONYM of 'Important'", options: ["Vital", "Trivial", "Minor", "Small"], answer: "Vital" },
    { question: "📘 SYNONYM of 'Answer'", options: ["Response", "Question", "Ask", "Demand"], answer: "Response" },
    { question: "📘 SYNONYM of 'Stop'", options: ["Halt", "Go", "Run", "Start"], answer: "Halt" },
    { question: "📘 SYNONYM of 'Hungry'", options: ["Starving", "Full", "Satisfied", "Content"], answer: "Starving" },
  ],

  18: [
    { question: "📘 SYNONYM of 'Angry'", options: ["Furious", "Peaceful", "Cool", "Happy"], answer: "Furious" },
    { question: "📘 SYNONYM of 'Clever'", options: ["Intelligent", "Dull", "Foolish", "Slow"], answer: "Intelligent" },
    { question: "📘 SYNONYM of 'Dark'", options: ["Obscure", "Light", "Bright", "Clear"], answer: "Obscure" },
    { question: "📘 SYNONYM of 'Difficult'", options: ["Challenging", "Easy", "Simple", "Plain"], answer: "Challenging" },
    { question: "📘 SYNONYM of 'Empty'", options: ["Vacant", "Full", "Occupied", "Filled"], answer: "Vacant" },
    { question: "📘 SYNONYM of 'Fast'", options: ["Speedy", "Slow", "Lazy", "Weak"], answer: "Speedy" },
    { question: "📘 SYNONYM of 'Gift'", options: ["Donation", "Curse", "Punishment", "Loss"], answer: "Donation" },
    { question: "📘 SYNONYM of 'Hope'", options: ["Optimism", "Fear", "Worry", "Despair"], answer: "Optimism" },
    { question: "📘 SYNONYM of 'Job'", options: ["Employment", "Unemployment", "Holiday", "Rest"], answer: "Employment" },
    { question: "📘 SYNONYM of 'Lazy'", options: ["Slothful", "Active", "Energetic", "Hardworking"], answer: "Slothful" },
  ],

  19: [
    { question: "📘 SYNONYM of 'Love'", options: ["Affection", "Hate", "Anger", "Dislike"], answer: "Affection" },
    { question: "📘 SYNONYM of 'Mistake'", options: ["Error", "Truth", "Correct", "Fact"], answer: "Error" },
    { question: "📘 SYNONYM of 'Nice'", options: ["Pleasant", "Ugly", "Bad", "Rude"], answer: "Pleasant" },
    { question: "📘 SYNONYM of 'Old'", options: ["Elderly", "Young", "Fresh", "Modern"], answer: "Elderly" },
    { question: "📘 SYNONYM of 'Poor'", options: ["Destitute", "Rich", "Wealthy", "Loaded"], answer: "Destitute" },
    { question: "📘 SYNONYM of 'Quiet'", options: ["Silent", "Noisy", "Loud", "Wild"], answer: "Silent" },
    { question: "📘 SYNONYM of 'Rich'", options: ["Prosperous", "Poor", "Weak", "Needy"], answer: "Prosperous" },
    { question: "📘 SYNONYM of 'Safe'", options: ["Protected", "Dangerous", "Risky", "Unsafe"], answer: "Protected" },
    { question: "📘 SYNONYM of 'Strong'", options: ["Mighty", "Weak", "Fragile", "Feeble"], answer: "Mighty" },
    { question: "📘 SYNONYM of 'Tall'", options: ["High", "Low", "Short", "Small"], answer: "High" },
  ],

  20: [
    { question: "📘 SYNONYM of 'Ugly'", options: ["Unattractive", "Beautiful", "Lovely", "Pretty"], answer: "Unattractive" },
    { question: "📘 SYNONYM of 'Victory'", options: ["Success", "Defeat", "Loss", "Failure"], answer: "Success" },
    { question: "📘 SYNONYM of 'Warm'", options: ["Heated", "Cold", "Chilly", "Cool"], answer: "Heated" },
    { question: "📘 SYNONYM of 'Weak'", options: ["Feeble", "Strong", "Tough", "Mighty"], answer: "Feeble" },
    { question: "📘 SYNONYM of 'Wise'", options: ["Prudent", "Foolish", "Silly", "Stupid"], answer: "Prudent" },
    { question: "📘 SYNONYM of 'Work'", options: ["Job", "Rest", "Play", "Stop"], answer: "Job" },
    { question: "📘 SYNONYM of 'Young'", options: ["Youthful", "Old", "Ancient", "Aged"], answer: "Youthful" },
    { question: "📘 SYNONYM of 'Yell'", options: ["Cry", "Whisper", "Murmur", "Talk"], answer: "Cry" },
    { question: "📘 SYNONYM of 'Happy'", options: ["Joyous", "Sad", "Upset", "Angry"], answer: "Joyous" },
    { question: "📘 SYNONYM of 'Angry'", options: ["Wrathful", "Calm", "Peaceful", "Joyful"], answer: "Wrathful" },
  ],
};

export default synonyms;
